CREATE = "Create_parking_lot"
PARK = "Park"
VACATE = "Leave"
SLOT_BY_CAR = "Slot_number_for_car_with_number"
SLOTS_BY_DRIVER_AGE = "Slot_numbers_for_driver_of_age"
REG_NO_BY_DRIVER_AGE = "Vehicle_registration_number_for_driver_of_age"
